### ISSUE TITLE
Issue migrating from lz4net to K4os.Compression.LZ4.Legacy

### ISSUE THREAD

**Issue by DAEADbE** [MiloszKrajewski/K4os.Compression.LZ4#52]
**Description**
I'm trying to migrate a code base to **K4os.Compression.LZ4.Legacy** from **lz4net** since it is no longer supported. I receive an **Unexpected end of stream** exception when trying to use the **CopyTo** function to a **MemoryStream**.
```
            var array = buf.ReadBytes((int) header.DecompressedSize);
            byte[] result = { };
            switch (header.CompressionType)
            {
                case CompressionType.NONE:
                    result = array;
                    break;
                case CompressionType.LZ4:
                case CompressionType.LZ4HC:
                    // Works fine - lz4net 1.0.15.93 (last version from nuget)
                    //result = LZ4Codec.Decode(array, 0, array.Length, (int) header.CompressedSize);

                    // Throws 'inputBuffer size is invalid or has been corrupted' - K4os.Compression.LZ4.Legacy 1.2.6
                    // Throws 'inputBuffer size is invalid or has been corrupted' - K4os.Compression.LZ4.Legacy 1.2.8-beta
                    //result = LZ4Legacy.Unwrap(array);

                    // Throws 'Unexpected end of stream' - K4os.Compression.LZ4.Legacy 1.2.6
                    // Throws 'Unexpected end of stream' - K4os.Compression.LZ4.Legacy 1.2.8-beta
                    using (var target = new MemoryStream())
                    {
                        using (var source = LZ4Legacy.Decode(new MemoryStream(array)))
                        {
                            source.CopyTo(target);
                        }
                        result = target.ToArray();
                    }
                    break;
                case CompressionType.LZMA:
                    break;
                default:
                    result = null;
                    break;
            }
```

**To reproduce**
```
            const string testString = "This is a test.";
            var stringBytes = Encoding.ASCII.GetBytes(testString);
            var lz4NetBytes = LZ4Codec.Encode(stringBytes, 0, stringBytes.Length); // Using lz4net to compress the string
            byte[] result;
            using (var target = new MemoryStream())
            {
                using (var source = LZ4Legacy.Decode(new MemoryStream(lz4NetBytes)))
                {
                    source.CopyTo(target);
                }
                result = target.ToArray();
            }
            Console.WriteLine(result.SequenceEqual(lz4NetBytes));
```

**Expected behavior**
Data from returned from the **LZ4Legacy.Decode** stream should be copied to the target **MemoryStream**.

**Actual behavior**
An **Unexpected end of stream** exception occurs when trying to use the **CopyTo** function to a **MemoryStream**.
```
Unhandled Exception: System.IO.EndOfStreamException: Unexpected end of stream
   at K4os.Compression.LZ4.Legacy.LZ4Stream.AcquireNextChunk()
   at K4os.Compression.LZ4.Legacy.LZ4Stream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at UBPU.Program.Main(String[] args)
```

**Environment**
 - CPU: Intel, 64-bit
 - OS: Windows 10
 - .NET: .NET Framework 4.7.2
 - LZ4: 1.2.6 & 1.2.8-beta
 - lz4net: 1.0.15.93

**Additional context**
Feel free to ask me any questions if you need any further context.

**Comment by MiloszKrajewski** [comment]
You overinterpreted when you need Legacy support. You need it ONLY when you used PICKLE (`Wrap`) or STREAM (`LZ4Stream`) protocols in lz4net.
As I can see you used regular BLOCK (`LZ4Codec.Encode`) protocol. So you don't need legacy support they are compatible out of the box:
```
lz4net.LZCodec.Encode == K4os.Compression.LZ4.LZCodec.Encode
lz4net.LZCodec.Encode == K4os.Compression.LZ4.LZCodec.Encode
```

No need for `MemoryStream`s and other shenanigans you use.

Hope it helps. 
If you still have problem with it let me know, I may find some time in the evening.

**Comment by DAEADbE** [comment]
Ah I see, my bad. Thanks for getting back to me so quickly, I've managed to fix it up and it is now working as expected.
