### ISSUE TITLE
Stream API CopyTo got NotSupportedException

### ISSUE THREAD

**Issue by overing** [MiloszKrajewski/K4os.Compression.LZ4#92]
I wrote a Stream test program according to the instructions in the README file, but got a NotSupportedException: Stream does not support reading error.

https://dotnetfiddle.net/UaL9Zg

Expected:
Print out "new { ReferenceEquals = false, SequenceEqual = true  }".

Actual behavior:
Unhandled exception. System.NotSupportedException: Stream does not support reading.
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at Program.Main(String[] args)

**Comment by MiloszKrajewski** [comment]
Not sure what you want to do but there is no bug here: `LZ4Stream.Encode(...)` creates a stream to be written to (Encode/Compress), so:

```csharp
using (var compressionStream = LZ4Stream.Encode(...))
    compressionStream.CopyTo(compressionOutput);
```

tries to read from stream which is write-only.

**Comment by overing** [comment]
My English is not very fluent
I apologize to you for my rudeness

This is the code I used to test
I expected it to work as described in the [stream compression chapter](https://github.com/MiloszKrajewski/K4os.Compression.LZ4/tree/master#stream-compression) in the README but I got an exception
By the way, my target framework is dotnet 6.0

```
'System.Private.CoreLib.dll': 'Stream does not support reading.'
   at System.ThrowHelper.ThrowNotSupportedException_UnreadableStream()
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
```

```cs
using System;
using System.IO;
using System.Linq;
using System.Text;
using K4os.Compression.LZ4.Streams;

var data = Encoding.UTF8.GetBytes("Try K4OS LZ4 Stream :)");

var compressionInput = new MemoryStream(data);
var compressionOutput = new MemoryStream(ushort.MaxValue);
using (var compressionStream = LZ4Stream.Encode(compressionInput, leaveOpen: true))
    compressionStream.CopyTo(compressionOutput);

var compressed = compressionOutput.ToArray();

var decompressionInput = new MemoryStream(compressed);
var decompressionOutput = new MemoryStream(ushort.MaxValue);
using (var decompressionStream = LZ4Stream.Decode(decompressionInput, leaveOpen: true, interactive: false))
    decompressionStream.CopyTo(decompressionOutput);

var decompressed = decompressionOutput.ToArray();
Console.WriteLine(new
{
    ReferenceEquals = ReferenceEquals(data, decompressed),
    SequenceEqual = Enumerable.SequenceEqual(data, decompressed),
});

Console.WriteLine("\n(press any key to exit)");
Console.ReadKey();
```
![image](https://github.com/MiloszKrajewski/K4os.Compression.LZ4/assets/12485392/24d886b1-f57f-43b9-b833-2cbf460b5aed)

**Comment by MiloszKrajewski** [comment]
It absolutely works as described in the [stream compression chapter](https://github.com/MiloszKrajewski/K4os.Compression.LZ4/tree/master#stream-compression) in the README but you misunderstood how it works.

Let me go through your code.

```csharp
var random = new Random();
var data = new byte[ushort.MaxValue];
random.NextBytes(data);
```

You don't understand the idea of random data. This is does not matter too much here as it will work with random bytes, but still, [you need to understand that](https://en.wikipedia.org/wiki/Randomness):

> [...] The central idea is that a string of bits is random if and only if it is shorter than any computer program that can produce that string [...], **which means that random strings are those that cannot be compressed** [...]

```csharp
var compressionOutput = new MemoryStream(ushort.MaxValue);
var compressionInput = new MemoryStream(ushort.MaxValue);
```

This pre-allocation might be useful in some high performance scenario, but this code, even after fixing obvious bugs is far from optimized, so it just makes things complex for no reason.

```csharp
compressionInput.SetLength(0);
compressionInput.Write(data, 0, data.Length);
compressionInput.Position = 0;
```

Writing it to stream, to copy it later is a waste of resources. LZ4 is a stream already, why not write it directly?

```csharp
using (var compressionStream = LZ4Stream.Encode(compressionInput, leaveOpen: true))
    compressionStream.CopyTo(compressionOutput);
```

This is bad in both lines. You switched input and output and then tried to copy in wrong direction.
The correct(-ish) version would be:

```csharp
using (var compressionStream = LZ4Stream.Encode(compressionOutput, leaveOpen: true))
    compressionInput.CopyTo(compressionStream);
```

```csharp
var compressed = compressionOutput.ToArray();
```

So you have `compressed` bytes... which you never use again!

```csharp
var decompressionOutput = new MemoryStream(ushort.MaxValue);
var decompressionInput = new MemoryStream(ushort.MaxValue);
```

Unnecessary pre-allocation again.

```csharp
decompressionInput.SetLength(0);
decompressionInput.Write(data, 0, data.Length);
decompressionInput.Position = 0;
```

This is also wrong, this should be `compressed` not `data`.

```csharp
using (var decompressionStream = LZ4Stream.Decode(compressionInput, leaveOpen: true))
    decompressionStream.CopyTo(decompressionOutput);
```

Not `compressionInput` but `decompressionInput`.

```csharp
var decompressed = decompressionOutput.ToArray();
Console.WriteLine(new
{
    ReferenceEquals = ReferenceEquals(data, decompressed),
    SequenceEqual = Enumerable.SequenceEqual(data, decompressed),
});
```

So bug-free code would be:

```csharp
using System;
using System.IO;
using System.Linq;
using K4os.Compression.LZ4.Streams;

public static class Program
{
    static void Main(string[] args)
    {
        var random = new Random();
        var data = new byte[ushort.MaxValue];
        random.NextBytes(data);

        var compressionOutput = new MemoryStream();
        var compressionInput = new MemoryStream();
        compressionInput.SetLength(0);
        compressionInput.Write(data, 0, data.Length);
        compressionInput.Position = 0;
		
        using (var compressionStream = LZ4Stream.Encode(compressionOutput, leaveOpen: true))
            compressionInput.CopyTo(compressionStream);
        var compressed = compressionOutput.ToArray();

        var decompressionOutput = new MemoryStream();
        var decompressionInput = new MemoryStream();
        decompressionInput.SetLength(0);
        decompressionInput.Write(compressed, 0, compressed.Length);
        decompressionInput.Position = 0;
		
        using (var decompressionStream = LZ4Stream.Decode(decompressionInput, leaveOpen: true))
            decompressionStream.CopyTo(decompressionOutput);
        var decompressed = decompressionOutput.ToArray();
		
        Console.WriteLine(new
        {
            ReferenceEquals = ReferenceEquals(data, decompressed),
            SequenceEqual = Enumerable.SequenceEqual(data, decompressed),
        });

        Console.WriteLine("\n(press any key to exit)");
        Console.ReadKey();
    }
}
```

after removing intermediate streams which are just consuming memory, faster version would be:

```csharp
using System;
using System.IO;
using System.Linq;
using K4os.Compression.LZ4.Streams;

public static class Program
{
    static void Main(string[] args)
    {
        var random = new Random();
        var data = new byte[ushort.MaxValue];
        random.NextBytes(data);

        var compressionOutput = new MemoryStream();
		
        using (var compressionStream = LZ4Stream.Encode(compressionOutput, leaveOpen: true))
            compressionStream.Write(data, 0, data.Length);

        compressionOutput.Position = 0;
        var decompressionOutput = new MemoryStream();

	var decompressed = new byte[data.Length];
        using (var decompressionStream = LZ4Stream.Decode(compressionOutput, leaveOpen: true))
            decompressionStream.Read(decompressed, 0, decompressed.Length);
		
        Console.WriteLine(new
        {
            ReferenceEquals = ReferenceEquals(data, decompressed),
            SequenceEqual = Enumerable.SequenceEqual(data, decompressed),
        });

        Console.WriteLine("\n(press any key to exit)");
        Console.ReadKey();
    }
}
```

**Comment by overing** [comment]
Code works successfully
Thank you very much for your help and advice
they are useful to me
